services:

  frontend:
    container_name: wolo-app-FE
    build:
      context: ./wolo-app
      dockerfile: Dockerfile_frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

  mail:
    container_name: smtp
    image: bytemark/smtp
    restart: always
    ports:
      - 25:587

  backend:
    container_name: wolo-app-api
    build:
      context: ./wolo-app-api
      dockerfile: Dockerfile_backend
    ports:
      - "8080:8080"
    env_file:
      - ./wolo-app-api/.env
    depends_on:
      - dbpostgresql
      - mail
      - translations
    restart: on-failure
    volumes:
      - wolo-app-api:/home/gradle/.gradle
    
  dbpostgresql:
    container_name: dbpostgresql
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./wolo-app-api/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: on-failure

  translations:
    container_name: wolo-app-ai
    build:
      context: ./Woloapp-AI
      dockerfile: Dockerfile_AI
    ports:
      - 5000:5000

volumes:
  db-data:
  wolo-app-api: